const {test, expect} = require('../../electron/testbase.js');

test('Button - orbit trackball with scroll ring', async ({ page }) => {
  const _slowMo = 150; // wait for 150 millisec for practice slow-move
  await page.waitForTimeout(_slowMo); await page.getByText('Orbit® Trackball with Scroll').click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'BUTTONS' }).click();
  await page.waitForTimeout(_slowMo); await page.getByText('Reset All').click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Okay' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'hover3' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Mute/ UnmuteZoomTeams' }).check();
  await expect.soft(page.getByRole('radio', {name:'Mute/ UnmuteZoomTeams' })).toBeChecked();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Camera On/ Camera OffZoomTeams' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Share Content/ Stop' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'End MeetingZoomTeams' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Screen Capture Capture screen' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Answer CallTeams' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Decline CallTeams' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Reset' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'AI Konnection' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'OpenAI ChatGPT' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Microsoft Copilot' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Google Gemini' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Reset' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Keyboard and Mouse' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Keyboard Shortcut' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Left Click', exact: true }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Right Click', exact: true }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Middle Click', exact: true }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Left Drag Click once to' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Right Drag Click once to' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Middle Drag Click once to' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Double Left Click' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Double Right Click' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Double Middle Click' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Triple Left Click' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Back' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Forward' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Click to Apply' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Hold to Apply' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Disable' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Reset' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Reset' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Productivity' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Undo' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Redo' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Cut' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Copy' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Paste' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Select All' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Find' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Open Application' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Open Website' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Open Folder' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Open File' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Back' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Forward' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Stop' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Refresh' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Maximize Window' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Minimize Window' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Close Window' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Show Next Window' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Minimize All' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Show Desktop' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Snap Window Right' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Snap Window Left' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Disable' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Reset' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Snippet' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'General' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Turn On/Off Mic' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Task Manager' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Lock Screen' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Open Explorer Window' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Show Run Dialog' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Show System Search' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Task View' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Play/Pause' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Stop' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Next Track' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Previous Track' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Volume Up' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Volume Down' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Volume Mute' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Scroll Up' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Scroll Down' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Scroll Left' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Scroll Right' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Track Scroll' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Auto Scroll' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Page Up' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Page Down' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Home' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'End' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'New Desktop' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Close Desktop' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Switch Desktop Left' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('radio', { name: 'Switch Desktop Right' }).check();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Disable' }).click();
  await page.waitForTimeout(_slowMo); await page.getByRole('button', { name: 'Reset' }).click();
});