const {test, expect} = require('../electron/testbase.js');

test('verify productivity buttons visible', async ({ page }) => {
  await page.getByText('Expert Mouse™ TB800 EQ').click();
  await page.getByRole('button', { name: 'hover8' }).click();
  await page.getByRole('button', { name: 'Productivity' }).click();
  await expect(page.locator('#root')).toContainText('Undo');
  await expect(page.locator('#root')).toContainText('Redo');
  await expect(page.locator('#root')).toContainText('Cut');
  await expect(page.locator('#root')).toContainText('Copy');
  await expect(page.locator('#root')).toContainText('Select All');
  await page.mouse.wheel(0, 50);
  await expect(page.locator('#root')).toContainText('Find');
  await expect(page.locator('#root')).toContainText('Open Application');
  await expect(page.locator('#root')).toContainText('Open Website');
  await expect(page.locator('#root')).toContainText('Open Folder');
  await expect(page.locator('#root')).toContainText('Open File');
  await page.mouse.wheel(0, 50);
  await expect(page.locator('#root')).toContainText('Back');
  await expect(page.locator('#root')).toContainText('Forward');
  await expect(page.locator('#root')).toContainText('Stop');
  await expect(page.locator('#root')).toContainText('Refresh');
  await expect(page.locator('#root')).toContainText('Maximize Window');
  await page.mouse.wheel(0, 50);
  await expect(page.locator('#root')).toContainText('Show Next Window');
  await expect(page.locator('#root')).toContainText('Minimize All');
  await expect(page.locator('#root')).toContainText('Show Desktop');
  await expect(page.locator('#root')).toContainText('Show Desktop');
  await expect(page.locator('#root')).toContainText('Snap Window Right');
  await expect(page.locator('#root')).toContainText('Snap Window Left');
});